on:
  pull_request:
    branches:
      - main
      - seperate
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter build apk --release --split-per-abi
      - run: flutter build appbundle --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/app/outputs/bundle/release/app-release.aab"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      # Remove the Apple (iOS) build steps
      # - run: flutter build ios --no-codesign
      # - run: cd build/ios/iphoneos
      # - run: mkdir Payload
      # - run: cd Payload
      # - run: ln -s ../Runner.app
      # - run: cd ..
      # - run: zip -r app.ipa Payload

      # Release Play Store
      - name: Upload to Play Store
        uses: google/play-developer-console-action@v2
        with:
          serviceAccountFile: ${{ secrets.GOOGLE_PLAY_SERVICES_JSON_KEY }}
          track: alpha  # Adjust track based on your release strategy
          apkReleaseFile: build/app/outputs/bundle/release/app-release.aab
          # Add other required parameters like packageName, changelog, etc.
